spring:
  data:
    mongodb:
      uri: mongodb+srv://jedirebels:anujqwerty32@cluster0.qr9uwh7.mongodb.net/CashFlowGo

app:
  currencyConversionUrl: https://mocki.io/v1/3a61dc8d-42cf-459f-9cf8-ce0512500642

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  api-docs:
    path: /api-doc